apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: swimie-ingress
  namespace: swimie-prod
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: swimie.life
    http:
	  paths:
	  - path: /
	    pathType: Prefix
		backend:
		  service:
		    name: swimie-server
			port:
			  number: 80
